version: "3.1"
services:
    apache-php:
        image: 'php:8.1.4-apache'
        container_name: buscaBinaria
        restart: always
        build:
            context: ./.devops/php
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - '9001:80'
        volumes:
            - .:/var/www/html/
            - ./.devops/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./.devops/apache/httpd.conf:/etc/apache2/conf-available/httpd.conf
            - ./.devops/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
        extra_hosts:
            - "host.docker-xdebug.internal:host-gateway"
        networks:
          - php-network
networks:
    php-network:
        driver: bridge
